version: '3.8'

services:
  mongo:
    image: docker.io/library/mongo:7
    container_name: threat-mongo
    environment:
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_DB: threat_db
    ports:
      - "27017:27017"

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/threat_db --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: threat-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: threat_db

    depends_on:
      mongo:
        condition: service_healthy
